import Link from "next/link";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import LoginBtn from "./LoginBtn";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/list" className="navbar-title">
            안녕하시긔
          </Link>
          <div className="navbar-down">
            <div>
              <Link href="/write">글싸기</Link>
              <Link href="/register">회원가입</Link>
            </div>
            <div>
              {session ? (
                <span>
                  와서 감사합니다 뻐큐 {session.user.name} <LogoutBtn />
                </span>
              ) : (
                <LoginBtn></LoginBtn>
              )}
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
