import Link from "next/link";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import LoginBtn from "./LoginBtn";
import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/list" className="navbar-title">
            <Image src="/pepe.jpg" alt="kermit" width={200} height={150} />
            <span> 이상한 사이트</span>
          </Link>
          <div className="navbar-down">
            <div>
              <Link href="/list" style={{ marginLeft: 310 }}>
                페이커 갤러리
              </Link>
              <Link href="/write">글싸기</Link>
              <Link href="/register">회원가입</Link>
            </div>
            <div style={{ marginLeft: 600 }}>
              {session ? (
                <span>
                  와서 감사합니다 {session.user.id}님 <LogoutBtn />
                </span>
              ) : (
                <LoginBtn></LoginBtn>
              )}
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
