import Link from "next/link";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import LoginBtn from "./LoginBtn";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/list" className="navbar-title">
            이 문구를 본 이상 희망을 버려라
          </Link>
          <div className="navbar-down">
            <Link href="/write">Write</Link>
            <Link href="/register">회원가입</Link>
            {session ? (
              <span>
                와서 감사합니다 뻐큐 {session.user.name} <LogoutBtn />
              </span>
            ) : (
              <LoginBtn></LoginBtn>
            )}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
